### ISSUE TITLE
Unused

### ISSUE THREAD

**Issue by Dixonapps** [jimmyd-be/Hardware-Monitor-Applet#6]
Hello,

So i cant get this software to work with my Logitech G15 v2.
Made a screen added stuff from HWInfo and completed the dialog.
after that all i get is a red message at the screen names with unused cant change anything.
And shows a black screen on the lcd display.

**Comment by jimmyd-be** [comment]
You need to 'order screen' first before the screen can be used.
The button to add the screens can be found in the right corner of the screen. In that dialog you need to place the created screen in the main track.
